<a href="https://colab.research.google.com/github/ReyesCarl/Numerical-Method/blob/main/Numeth_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numerical Method
###Matrix and its operation
###Reyes, Carl Vincent G.
####8/31/2021





In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3]) #This is a 1x3 array
print(a)

[1 2 3]


In [13]:
b = np.array([[1,2,3],[4,5,6]]) #This is a 2x3 matrix 
b [0,0] = 8
print("b = "  +str(b))
print("The shape of a is " + str(a.shape))
print(b.shape)

b = [[8 2 3]
 [4 5 6]]
The shape of a is (3,)
(2, 3)


In [16]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]]) #A 3x3 matrix
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
d = np.full((2,2),5)
print(d)

[[5 5]
 [5 5]]


In [19]:
e = np.eye(2)
print(e)

[[1. 0.]
 [0. 1.]]


In [25]:
f = c
f = np.diagonal(f)
print(f)

[1 5 9]


In [26]:
g = np.empty((0,10))
print(g)

[]


In [32]:
h = np.zeros((2,2))
print(h)

[[0. 0.]
 [0. 0.]]


In [33]:
print(e+h)

[[1. 0.]
 [0. 1.]]
