<a href="https://colab.research.google.com/github/ReyesCarl/Numerical-Method/blob/main/Python_Exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Reyes, Carl Vincent G. 
###Matrix and Its Operations

In [1]:
import numpy as np

In [13]:
A = np.array([[-5,0],
     [4,2]])

In [3]:
B = np.array([[6,-3],
     [2,3]])

In [14]:
C = A+B
print(C)

[[ 1 -3]
 [ 6  5]]


In [16]:
D = B - A
print(D)

[[11 -3]
 [-2  1]]


In [17]:
E = A-B
print(E)

[[-11   3]
 [  2  -1]]
