<a href="https://colab.research.google.com/github/ReyesCarl/Numerical-Method/blob/main/Reyes_Carl_linalg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Determinants for matrices


In [ ]:
import numpy as np 


In [12]:
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]])
print(A)
print(np.linalg.det(A))
print(round(np.linalg.det(A)))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
-13.999999999999996
-14
